## **Intro**

In [1]:
import numpy as np
n1=np.array([1,2,3,4,5])
n1
type(n1)
n1

array([1, 2, 3, 4, 5])

In [2]:
n2=np.array([[1,2,3,4],[2,3,6,8]])
n2


array([[1, 2, 3, 4],
       [2, 3, 6, 8]])

In [3]:
n1=np.zeros([1,2])
n1
n2=np.zeros([5,5])
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [5]:
n1=np.arange(1,11)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
n1=np.arange(1,11,2)
n1

array([1, 3, 5, 7, 9])

In [7]:
n1=np.random.randint(1,100,5)
n1

array([83, 71, 54, 31, 57])

# **Numpy Operations**

In [8]:
n1=np.array([[1,2,3],[4,7,6]])
n1.shape

(2, 3)

In [9]:
n1.shape=(3,2)
n1

array([[1, 2],
       [3, 4],
       [7, 6]])

In [10]:
#vstack()

n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.vstack((n2,n1))

array([[4, 5, 6],
       [1, 2, 3]])

In [12]:
#hstack()
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [13]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.hstack((n2,n1))

array([4, 5, 6, 1, 2, 3])

In [14]:
#column_stack()
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.column_stack((n2,n1))

array([[4, 1],
       [5, 2],
       [6, 3]])

In [16]:
#inttersect1d()
n1=np.array([10,20,30,40,50,60])
n2=np.array([40,50,60,70,80,90,100,70])
np.intersect1d(n1,n2)

array([40, 50, 60])

In [17]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([40,50,60,70,80,90,100,70])
np.intersect1d(n2,n1)

array([40, 50, 60])

In [18]:
#setdiff1d
n1=np.array([10,20,30,40,50,60])
n2=np.array([40,50,60,70,80,90,100,70])
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [19]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([40,50,60,70,80,90,100,70])
np.setdiff1d(n2,n1)

array([ 70,  80,  90, 100])

# **Numpy Mathematics**

In [20]:
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2]) #sum of all elements


np.int64(100)

In [21]:
np.sum([n1,n2],axis=0) #axis=0 is the sum based on column

array([40, 60])

In [22]:
np.sum([n1,n2],axis=1) #axis=1 is the sum based on row

array([30, 70])

In [23]:
#basic arithmetic operations
n1=np.array([10,20,30])
n1+5


array([15, 25, 35])

In [24]:
n1-5

array([ 5, 15, 25])

In [25]:
n1*2

array([20, 40, 60])

In [26]:
n1/5

array([2., 4., 6.])

In [27]:
np.mean(n1)

np.float64(20.0)

In [28]:
n2=np.array([10,20,30,40])
np.median(n2)

np.float64(25.0)

In [29]:
np.std(n1)

np.float64(8.16496580927726)

# **Numpy Matrix**

In [30]:
n1=np.array([[10,20,30],[20,15,2],[5,4,6]])
n1

array([[10, 20, 30],
       [20, 15,  2],
       [ 5,  4,  6]])

In [31]:
n1[1]

array([20, 15,  2])

In [32]:
n1[:,1]

array([20, 15,  4])

In [33]:
n1[0:,2]

array([30,  2,  6])

In [34]:
#transpose
np.transpose(n1)

array([[10, 20,  5],
       [20, 15,  4],
       [30,  2,  6]])

In [35]:
n2=np.array([[2,3,4],[2,5,4],[5,2,6]])
n2

array([[2, 3, 4],
       [2, 5, 4],
       [5, 2, 6]])

In [36]:
n1.dot(n2)

array([[210, 190, 300],
       [ 80, 139, 152],
       [ 48,  47,  72]])

In [37]:
n2.dot(n1)

array([[100, 101,  90],
       [140, 131,  94],
       [120, 154, 190]])

#Load/save numpy array

In [38]:
n1=np.array([10,20,30,40,50,60])
np.save('shadin',n1)
n1

array([10, 20, 30, 40, 50, 60])

In [39]:
n2=np.load('shadin.npy')
n2

array([10, 20, 30, 40, 50, 60])